<?php

namespace Container71HAeN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2S3es2tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2S3es2t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2S3es2t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'habitatRepository' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
        ], [
            'habitatRepository' => 'App\\Repository\\HabitatRepository',
        ]);
    }
}
