<?php

namespace Container71HAeN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LjXPu8dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LjXPu8d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LjXPu8d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccueilController::index' => ['privates', '.service_locator.mBk6gb2', 'get_ServiceLocator_MBk6gb2Service', true],
            'App\\Controller\\ConnecteController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.NDmick5', 'get_ServiceLocator_NDmick5Service', true],
            'App\\Controller\\HabitatController::getHabitats' => ['privates', '.service_locator.2S3es2t', 'get_ServiceLocator_2S3es2tService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.DS05KeC', 'get_ServiceLocator_DS05KeCService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.DS05KeC', 'get_ServiceLocator_DS05KeCService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\UtilisateurController::register' => ['privates', '.service_locator.YUNSPEp', 'get_ServiceLocator_YUNSPEpService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AccueilController:index' => ['privates', '.service_locator.mBk6gb2', 'get_ServiceLocator_MBk6gb2Service', true],
            'App\\Controller\\ConnecteController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.NDmick5', 'get_ServiceLocator_NDmick5Service', true],
            'App\\Controller\\HabitatController:getHabitats' => ['privates', '.service_locator.2S3es2t', 'get_ServiceLocator_2S3es2tService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.DS05KeC', 'get_ServiceLocator_DS05KeCService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.DS05KeC', 'get_ServiceLocator_DS05KeCService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.t6i3vFk', 'get_ServiceLocator_T6i3vFkService', true],
            'App\\Controller\\UtilisateurController:register' => ['privates', '.service_locator.YUNSPEp', 'get_ServiceLocator_YUNSPEpService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AccueilController::index' => '?',
            'App\\Controller\\ConnecteController::login' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\HabitatController::getHabitats' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\UtilisateurController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AccueilController:index' => '?',
            'App\\Controller\\ConnecteController:login' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\HabitatController:getHabitats' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\UtilisateurController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
