<?php

namespace ContainerA945oBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDmick5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NDmick5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NDmick5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'compteurService' => ['privates', 'App\\Service\\CompteurService', 'getCompteurServiceService', true],
        ], [
            'compteurService' => 'App\\Service\\CompteurService',
        ]);
    }
}
