<?php

namespace ContainerA945oBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatelessAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\StatelessAuthenticator' shared autowired service.
     *
     * @return \App\Security\StatelessAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/StatelessAuthenticator.php';

        return $container->privates['App\\Security\\StatelessAuthenticator'] = new \App\Security\StatelessAuthenticator(($container->privates['App\\Repository\\UtilisateurRepository'] ?? $container->load('getUtilisateurRepositoryService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
