controllers:
    resource: ../src/Controller/
    type: annotation

# config/routes.yaml
contact_form:
    path: /contact
    controller: App\Controller\ContactController::sendEmail


connexion_connexions:
    path: /connexion
    controller: App\Controller\ConnecteController::login


app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
