<?php

namespace ContainerWniUVmK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MBk6gb2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mBk6gb2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mBk6gb2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
        ], [
            'animalRepository' => 'App\\Repository\\AnimalRepository',
        ]);
    }
}
