<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuFHZzQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuFHZzQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZuFHZzQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZuFHZzQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZuFHZzQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZuFHZzQ',
    'container.build_id' => 'ae8387cd',
    'container.build_time' => 1732120674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuFHZzQ');
