<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIUvKhG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIUvKhG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIUvKhG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIUvKhG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHIUvKhG\App_KernelDevDebugContainer([
    'container.build_hash' => 'HIUvKhG',
    'container.build_id' => '9f3a3ad4',
    'container.build_time' => 1728302907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIUvKhG');
