<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJwhysUz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJwhysUz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJwhysUz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJwhysUz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJwhysUz\App_KernelDevDebugContainer([
    'container.build_hash' => 'JwhysUz',
    'container.build_id' => 'fa7cceee',
    'container.build_time' => 1732159437,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJwhysUz');
